openapi: 3.0.0
info:
  title: Glashaus API
  version: 1.0.0
paths:
  /audit:
    post:
      summary: Initiate an Audit for a specific Listing URL
      responses:
        '200':
          description: Audit Queued
